services:
  db:
    image: postgres:16
    container_name: starnavi_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5433"

  api:
    build:
      context: .
    container_name: starnavi_api
    volumes:
      - apidata:/app
    env_file:
      - .env
    ports:
      - "7777:8000"
    depends_on:
      db:
        condition: service_healthy
    command: ["/starnavi/docker/app.sh"]

volumes:
    postgresdata:
    apidata: