services:
  api:
    build:
      context: .
    container_name: starnavi_api
    volumes:
      - apidata:/app
    env_file:
      - .env
    ports:
      - "8080:8000"
    depends_on:
      - db
    command: [ "/starnavi/docker/app.sh" ]

  db:
    image: postgres:16
    container_name: starnavi_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
    postgresdata:
    apidata: